name: Update Dependencies

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    if: github.repository_owner == github.actor # Only run on main repository

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install pip-tools
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools

    - name: Update requirements
      run: |
        # Update main requirements
        pip-compile --upgrade requirements.in -o requirements.txt
        
        # If you have development requirements
        # pip-compile --upgrade requirements-dev.in -o requirements-dev.txt

    - name: Check for changes
      id: changes
      run: |
        if git diff --exit-code requirements.txt; then
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Create Pull Request
      if: steps.changes.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update Python dependencies"
        title: "chore: update Python dependencies"
        body: |
          ## Automated Dependency Update
          
          This PR updates Python dependencies to their latest compatible versions.
          
          ### Changes
          - Updated dependencies in `requirements.txt`
          
          ### Testing
          - [ ] All existing tests pass
          - [ ] No breaking changes introduced
          - [ ] Security vulnerabilities addressed
          
          This PR was created automatically by the dependency update workflow.
        branch: automated/update-dependencies
        delete-branch: true